### ISSUE TITLE
Добавить ответы API для лабораторной 1

### ISSUE THREAD

**Issue by vekrasikov** [Yutalina/TryAgain#1]
Ответы разработанных апи предоставлять обязательно. См. https://stepik.org/lesson/212655/step/1?unit=185868

Также, https://github.com/Yutalina/TryAgain/commit/670f9f057f926b948896030ffaebfedac4ff7664#commitcomment-32873302

**Comment by Yutalina** [comment]
> Ответы разработанных апи предоставлять обязательно. См. https://stepik.org/lesson/212655/step/1?unit=185868
> 
> Также, [670f9f0#commitcomment-32873302](https://github.com/Yutalina/TryAgain/commit/670f9f057f926b948896030ffaebfedac4ff7664#commitcomment-32873302)

"Если в критерии лабораторной указано, что необходимо сохранить результат работы разработанных API" - в лабораторной же не указано

Критерии выполнения лабораторной:
Разработаны APIs из расчёта одна функция - одно API;
Каждая функция отрабатывает корректно.

**Comment by vekrasikov** [comment]
Читайте введение внимательно. Так сказано "Общие критерии выполнения лабораторных работ". Общие, значит распространяются на все, если в лабораторной не написано обратного.

**Comment by vekrasikov** [comment]
В лабораторной 1 не указано, что не нужно сохранять результаты работы АПИ. Значит это необходимо сделать.

**Comment by Yutalina** [comment]
> В лабораторной 1 не указано, что не нужно сохранять результаты работы АПИ. Значит это необходимо сделать.

Хорошо, я поняла. Извините, а сама лабораторная выполнена верно? Не в том плане работает или нет, а сам метод выполнения? (Когда я добавлю ответы, она будет зачтена?)

**Comment by vekrasikov** [comment]
Если с ответами всё ок будет, то да.
